feat: add csv export
premieroctet/next-admin pull request #89
Opened 2023-12-11 17:19 UTC by foyarash

![image](https://github.com/premieroctet/next-admin/assets/11079152/a2a31d66-6112-47e1-8282-e8ebc8563961)

2023-12-13 17:27 UTC, tlenclos requested changes
It should be full server side with proper download header, see for example `Content-Disposition: attachment; filename="export-user.csv"`.
I don't think we have to create an api endpoint, we could just return a CSV response.

Also it should be streamed to avoid out of memory issue (ie : exporting a big CSV file should be possible with a low memory node process).

2023-12-14 13:17 UTC, foyarash commented
> It should be full server side with proper download header, see for example `Content-Disposition: attachment; filename="export-user.csv"`. I don't think we have to create an api endpoint, we could just return a CSV response.
> 
> Also it should be streamed to avoid out of memory issue (ie : exporting a big CSV file should be possible with a low memory node process).

We are going to support streaming only for Page Router, as its not supported yet for Server Actions.

2024-01-02 20:35 UTC, colin27091 approved these changes

2024-05-06 12:48 UTC, tlenclos commented
Closing this since we won't support this directly inside next-admin for now, however we will add a new "Recipes" section in the documentation with an export example.

See https://github.com/premieroctet/next-admin/issues/265

2024-05-06 12:48 UTC, closed without merging